### ISSUE TITLE
"Failed to link yarn modules" if project uses a vendored yarn of newer version

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restylers#928]
It seems common to configure a project to vendor a newer/specific version of `yarn`. If it's too new, our shim that links our prettier plugins doesn't work:

```
2025-02-23 18:55:16 [info     ] Running prettier-json on package.json
Failed to link yarn modules
Please report this as an issue
https://github.com/restyled-io/restylers/issues
```

This is because the `--offline` flag we use was removed:

```console
root@e785a29a9d97:/code# yarn --offline link tailwindcss @trivago/prettier-plugin-sort-imports
Unknown Syntax Error: Unsupported option name ("--offline").
```

If we remove that flag though, `link` doesn't work at all anymore:

```console
root@e785a29a9d97:/code# yarn link tailwindcss @trivago/prettier-plugin-sort-imports
Usage Error: Invalid destination 'tailwindcss'; Can't link the project to itself
```

🤷 

Some ideas:

1. Figure out how do this with newer yarn and do that, perhaps conditionally
2. Figure out how to use the `yarn` in our image even if the project has one vendored
3. Don't consider this fatal, warn about it and proceed -- then only folks using both newer/vendored yarn *and* one of these plugins would be broken

Help welcome!

**Comment by pbrisbin** [comment]
As a workaround for users that don't actually need these plugins, you can configure `command` to bypass our shim that calls `yarn link`:

```yaml
restylers:
  - prettier:
      command:
        - /app/node_modules/.bin/prettier
        - --write
  - "*"
```

Since this applies to all `prettier`-based images, you can use a Yaml anchor/reference to configure them all:

```yaml
restylers:
  - prettier: &prettier
      command:
        - /app/node_modules/.bin/prettier
        - --write
  - prettier-json:
      <<: *prettier
  - prettier-markdown:
      <<: *prettier
  - prettier-yaml:
      <<: *prettier
  - "*"
```

We could consider making these the new defaults for the `prettier-*` images, which have no need for the JavaScript-formatting plugins.
